## NumPy入門3
NumPy内に用意されたarrayについてこれまでは基本的な演算やデータの取り扱いについて学んできた。ここからは、発展的な内容として、arrayで重要となるブロードキャストという機能や、数学、線形代数と対応した演算を見ていこう。

まずはNumPyをインポートしよう。

In [1]:
import numpy as np

### 1. ブロードキャスト
例えば以下の様に構造の違う2つのarrayを用意。

In [2]:
a3 = np.array([1, 2, 3])
a3_3 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(a3.shape)
print(a3_3.shape)

(3,)
(3, 3)


線形代数では、この様な構造の違う行列やベクトルの和や差は計算できない。では、この2つのarrayはどうだろう？

In [3]:
print(a3)
print(a3_3)
print(a3+a3_3)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[2 4 6]
 [2 4 6]
 [2 4 6]]


できた！

NumPyは構造の違うarrayどうしを計算しようとした際、自動で調整して計算してくれる。この様な機能を __ブロードキャスト__ という。
もちろんこれは、加算乗除全てで可能だ。

では、arrayではどの様な計算ができて、どの様な計算ができないのか確かめておこう。

In [4]:
a1 = np.array([1])
a4 = np.array([1, 2, 3, 4])
a3_4 = np.array( [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
a3_1 = np.array( [[1], [1], [1]])

これらの色々な組み合わせで計算してみて、計算が可能か確かめてみよう。

In [6]:
print(a4)
print(a3)
print(a4 + a3)

[1 2 3 4]
[1 2 3]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

これは計算できない。

同じ階数でも、次元が違う計算はできないみたいだ。もちろんこの様な場合もできない。

In [7]:
print(a3_3)
print(a3_4)
print(a3_3 + a3_4)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

ただし例外がある。一次元のデータは、次元が大きい方のデータに合わせて全てが同じ値のデータに修正して計算してくれる様だ。

例えば以下の場合、1次元データの方が __全ての要素が1のデータに修正されて計算されている。__

In [8]:
print(a1)
print(a3)
print(a1 + a3)

[1]
[1 2 3]
[2 3 4]


先ほど(3,3) と(3,)の和は計算できていたが、(3,4)と(3,)の和は計算できない。

In [9]:
print(a3_4)
print(a3)
print(a3_4 + a3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[1 2 3]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

(3,4)と(4,)の和にすれば計算が可能となる。

In [10]:
print(a3_4)
print(a4)
print(a3_4 + a4)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[1 2 3 4]
[[2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]]


このように階数の異なるarray同士の演算の場合、「より後ろにある軸の要素数が一致している場合」に計算が可能となる、つまり「前の方にある軸を補うようにブロードキャストが行われる」

In [11]:
print(np.zeros((2,3,4,5)) + np.zeros((4,5)))
print(np.zeros((2,3,4,5)) + np.zeros((2,3,4)))

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


ValueError: operands could not be broadcast together with shapes (2,3,4,5) (2,3,4) 

#### ブロードキャストの性質まとめ

- 階数(ndimの値)があっていない場合
  - 後ろの軸の要素数が一致している場合は自動で同じ要素を繋げ大きい方に合わせられる
  - 後ろの軸の要素数が一致していない場合は計算できない
- 階数があっていても(いなくても)、各次元のサイズ(shapeの値)があっていなければ計算できない
- ただし例外的に、`[1]`や`[[1], [1]]`の様に次元が1の場合は同じ要素を繰り返すことで要素数を自動で合わせられる

__あとは、思いつく限り色々なデータを作成して計算してみて、ブロードキャストの感覚を掴んでおこう。__

### 2. 数学とNumPy
数学で学んだ様々な計算について、NumPyでどの様にできるのかも確かめておこう。NumPyはこの様な計算をするにも非常に便利なのである。

#### べき乗とルート
これはPythonの標準機能でも`**`で計算できるが、NumPyでも以下の様な機能が提供されている。

In [12]:
#10の2乗
print(np.power(10, 2))

#100の1/2乗
print(np.power(100, 0.5))

#100のルート
print(np.sqrt(100))

100
10.0
10.0


#### 数学に登場する様々な定数
数学では様々な定数が登場した。NumPyではその定数も提供されているため、手入力で実装する必要がない。

In [13]:
#円周率
print(np.pi)

#自然対数の底
print(np.e)

3.141592653589793
2.718281828459045


#### 三角関数
様々な三角関数を計算する機能も以下の様に提供されている。ここでは紹介しきれないが、他にも様々な関数が用意されているので調べてみてほしい。

In [14]:
#sin
print(np.sin(np.pi/2))

#cos
print(np.cos(np.pi))

#tan
print(np.tan(np.pi))

#arcsin (sinの逆関数)
print(np.arcsin(0))

#arccos (cosの逆関数)
print(np.arccos(0))

#arctan (tacの逆関数)
print(np.arctan(0))

1.0
-1.0
-1.2246467991473532e-16
0.0
1.5707963267948966
0.0


ただし、これらの計算はあくまでコンピュータ内でアルゴリズムを用いて近似的に計算されるため誤差が生じる。0となるべき値が0ではなくe-16などと非常に小さい値となっていることがわかる。

#### ランダム
乱数を出力する機能はrandomモジュールにもあったが、NumPyにも便利な機能が提供されている。

以下の様に`random.rand`を用いれば、要素が全て0~1の乱数である指定した構造のarrayが生成できる。ここでは2行3列のarrayを生成した。

In [15]:
rand_data = np.random.rand(2, 3)

print(rand_data)

[[0.69000458 0.07177353 0.99785565]
 [0.86503237 0.49744371 0.30239466]]


### 3. 線形代数とNumPy
NumPyが提供するarrayは、様々なデータを表現できる。そのデータはベクトルや行列を含むテンソルとして、多重な構造を扱うのにも便利である。

では、線形代数で学んだ様々な計算をarrayで実施するにはどの様にすればいいのか、ここで見ておこう。ここを理解すれば、線形代数で学んだ様々な計算をコンピュータで自動化できる。複雑で数の多い計算も正確に素早く実行することができる。

#### 単位行列
NumPyに用意された`identity()`という関数は、引数で指定したサイズの単位行列を返す。

以下では3行3列の単位行列を作成してみる。

In [16]:
mat_id = np.identity(3)

print(mat_id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 行列と積
arrayで表現した行列は、単に`*`を用いると要素積となる。

以下の計算を見ると行列積ではなく要素積となっていることがわかる。

In [17]:
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(mat1 * mat_id)

[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


べき乗の計算も同じく要素ごとのべき乗である。

これは`**`というPython標準の記法を用いても、`np.power()`を用いても同じである。

In [18]:
print(mat1 **2)
print(np.power(mat1, 2))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


ベクトルの内積や行列積を計算するためには`dot()`という関数を使う。

引数には、かける順番で入力する。

In [19]:
print(np.dot(mat1, mat_id))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [20]:
vec1 = np.array([1,2,3])
vec2 = np.array([3,4,5])

print(np.dot(vec1, vec2))

26


ベクトルの内積は`np.inner()`でも行える。また、`dot()`の代わりに`matmul()`を利用してもよい

In [21]:
print(np.inner(vec1, vec2))

26


#### 行列の転置
行列の転置を計算する方法は以下の3つある。計算結果は全て同じなので、使いやすいものを使うといい。

In [22]:
print(mat1.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [23]:
print(mat1.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [24]:
print(np.transpose(mat1))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### ノルム
ノルムの計算は`linalg.norm()`を使用すればいい。ただし、ノルムの種類は`ord`という引数で指定する。

例えば以下は、`vec1`について順にL1ノルム、L2ノルム、L3ノルムである。

In [25]:
print(np.linalg.norm(vec1, ord=1))
print(np.linalg.norm(vec1, ord=2))
print(np.linalg.norm(vec1, ord=3))

6.0
3.7416573867739413
3.3019272488946263


行列についても同様にノルムを計算できる。

In [26]:
print(np.linalg.norm(mat1, ord=2))

16.84810335261421


ちなみに、各要素の絶対値をarrayで返す`abs()`と全ての要素をたす`sum()`等を用いて以下の様に計算することもできる。

In [27]:
print(np.sum(np.abs(vec1)))
print(np.sqrt(np.sum(np.abs(vec1**2))))
print(np.power(np.sum(np.abs(vec1**3)), 1/3))

6
3.7416573867739413
3.3019272488946263


## 最後に
ここまでで紹介したarrayやNumPyの様々な機能は頻出なものの一部である。他にも便利な機能がたくさんあるので、「こういうことができないのかな？」と思った際に積極的に調べてみるのが今後の学習を加速させるために非常に重要となる。

また、ここで紹介した内容についても知識としてだけではなく自身でも手を動かし、色々なパターンでarrayを作成して計算して感覚を掴んでいこう。